### ISSUE TITLE
InstituteKennung.pdf files are requested but not included in the template arts

### ISSUE THREAD

**Issue by davidhaller** [FAU-AMMN/fau-beamer#14]
In beamerposterthemefau.sty, [line 66](https://github.com/FAU-AMMN/fau-beamer/blob/f1e02bbae4b907256f3a87e1922bb6a4a553166b/styles/beamerposterthemefau.sty#L66), a file named InstituteKennung.pdf is requested, but such files are not provided by the [template arts downloads](https://www.intern.fau.de/kommunikation-marketing-und-corporate-identity/vorlagen/praesentationsvorlagen-powerpoint/) (only InstituteKennungWhite.pdf). Therefore, the poster build fails / shows default error image even after placing all files from the zip in the requested directory.

**Comment by TimRoith** [comment]
Yes, I already produced the new .zip files a while ago. Unfortunately I do not have the rights to upload them directly to the website but instead I have to mail them to someone who then uploads them.

I will request to upload to new files again and hope that they are available soon.

**Comment by TimRoith** [comment]
That is a very good question, that has been going on for a long time now. Unfortunately, I am not allowed to upload them. I am in contact with people from the corporate team and currently I should not upload them here.

I'm actively trying to change that fact, since it would so much easier for everyone to just provide the files here. Furthermore the reasons for me not being allowed to provide them here are a bit vague, so I am hoping this will change soon. Until then we have to live with this inconvenient solution.

**Comment by TimRoith** [comment]
The new .zip files are available now, therefore I'll close this issue for now. The logo file situation is however not fully satisfactory yet.
