### ISSUE TITLE
Linebreak in title

### ISSUE THREAD

**Issue by Rikorose** [FAU-AMMN/fau-beamer#9]
Hi there, thanks for the template.

Due to a long title, I want to include a line break in the title page. Just adding `\\` does not seem to work:
```tex
title{Some very long title \\ that needs a line break}
```

```
(/usr/share/texlive/texmf-dist/tex/latex/lm/ot1lmtt.fd
File: ot1lmtt.fd 2015/05/01 v1.6.1 Font defs for Latin Modern
)
<_art/TFTitle.jpg, id=50, 963.6pt x 542.025pt>
File: _art/TFTitle.jpg Graphic file (type jpg)
<use _art/TFTitle.jpg>
Package pdftex.def Info: _art/TFTitle.jpg  used on input line 134.
(pdftex.def)             Requested size: 963.41032pt x 413.34811pt.
LaTeX Font Info:    Font shape `T1/phv/b/n' will be
(Font)              scaled to size 29.43994pt on input line 134.


! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.134   \end{frame}   <- This is the title frame
                   
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

```

**Comment by TimRoith** [comment]
Hi thanks for reporting!

Are you using the code downloaded from the FAU website or from the git? Because unfortunately the upload of the code to the website is done manually and therefore the version there is always a bit outdated.

### Tests on the newest version

I just pushed a minor update and tested the line breaks

```
\title[fau-beamer]{The NEW fau-beamer Demo\\ with a two line title}
```

which results in 

![image](https://user-images.githubusercontent.com/44805883/162591545-d4b0db1e-eeb3-40af-9ff8-6ace8e63249b.png)

Also since the title text is now put in a parbox, longer content should break automatically

```
\title[fau-beamer]{The NEW fau-beamer Demo with a very, very, very, very, very long title}
```

![image](https://user-images.githubusercontent.com/44805883/162591605-e9a22547-489f-4578-b40e-13bfec7ff9e7.png)


If you experience the same issue with the new version I have to try to reproduce the error.

**Comment by Rikorose** [comment]
Hi, I was using an old version. Works now, thanks!
